// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zngfcxlnlyyxdsvjlinr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZ2ZjeGxubHl5eGRzdmpsaW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTYzMzIsImV4cCI6MjA2NzM5MjMzMn0.Q-_xJxC-TtU_xll-F5ViF_SORSsR3DHMlZRqa6FLEUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});